#  (c) Copyright 2022 Palantir Technologies Inc. All rights reserved.
"""Execution class to define a compute function."""
from transforms.api import Input, Output, transform

from palantir_models.transforms._model import ModelInput


@transform(
    model=ModelInput("model_rid", "model_version_rid"),
    input_dataset=Input("input_dataset"),
    output_dataset=Output(),
)
def batch_execution(model, input_dataset, output_dataset):
    """Note for now only supporting a single input and single output. Leaving the alias for output_dataset as empty/None
    so that the transform is unbound. This is required so that the transform's reference field does not have an output
    hash appended. We can't have an output hash appended, because the compute_function within jobspec generated by
    ml-server/the Objectives system doesn't have a hash."""
    model.transform_write(input_dataset, output_dataset)


__all__ = ["batch_execution"]
